/*
 * @Description: 请补充模块描述
 * 
 * @Author: liaoxiangsui
 * @Date: 2024-03-02 12:58:57
 * 
 * Copyright © 2014-2024 Rabbitpre.com. All Rights Reserved.
 */
import { Inter } from "next/font/google";
import { Header } from "@/components/Header";
import "@/app/globals.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'AI CLUB',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}